export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUB_QUANTITY = "SUB_QUANTITY";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNIN = "USER_SIGNIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const EMPTY_PRODUCT_CART = "EMPTY_PRODUCT_CART";
export const USER_BALANCE = "USER_BALANCE";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";


